const projects = [
  { id: 'authenticity', title: 'What can we trust in a digital image?', label: 'Image authenticity', type: 'vision', status: 'Ongoing', year: '2026', summary: 'Watermarking, deepfake detection, and manipulation localization meet at one question: what evidence survives transformation?', methods: ['Watermark robustness', 'Paired real / fake evaluation', 'Localization and mask comparison'], visual: 'image' },
  { id: 'robustness', title: 'Where does a model break?', label: 'Adversarial learning', type: 'robustness', status: 'Experimental', year: '2026', summary: 'We stress clean assumptions with perturbations, poisoning, backdoors, and transfer attacks to map failure instead of hiding it.', methods: ['Perturbation sweeps', 'Training-data corruption', 'Class-level failure analysis'], visual: 'code' },
  { id: 'landscapes', title: 'How do images help us read a landscape?', label: 'Remote sensing', type: 'vision', status: 'Baseline', year: '2025', summary: 'A reproducible thread connecting RGB imagery, vegetation labels, and the evaluation details that shape an ecological claim.', methods: ['Baseline modeling', 'Class construction', 'Imbalance analysis'], visual: 'ndvi' },
  { id: 'next', title: 'What should we investigate next?', label: 'Open question', type: 'systems', status: 'Open slot', year: 'NEXT', summary: 'A permanent place for the next direction. The group stays coherent because the process matters more than one semester topic.', methods: ['Define the question', 'Collect evidence', 'Document limitations'], visual: 'note' }
];
const members = [
  { initials: 'PM', name: 'Project manager', role: 'PM', detail: 'Direction / coordination' }, { initials: 'CP', name: 'Co-project manager', role: 'Co-PM', detail: 'Planning / technical lead' }, { initials: 'M1', name: 'Research member', role: 'Member', detail: 'Question / contribution' }, { initials: 'M2', name: 'Research member', role: 'Member', detail: 'Question / contribution' }, { initials: 'AD', name: 'Faculty advisor', role: 'Advisor', detail: 'Mentorship / context' }
];
const viewNames = ['home', 'work', 'lab', 'people'];
const views = [...document.querySelectorAll('[data-view]')];
const setView = (name) => { const next = viewNames.includes(name) ? name : 'home'; views.forEach(view => { view.hidden = view.dataset.view !== next; }); document.querySelectorAll('[data-view-link]').forEach(link => link.classList.toggle('current', link.dataset.viewLink === next)); document.title = next === 'home' ? 'PandaHat / Research in public' : `PandaHat / ${next}`; window.scrollTo({ top: 0, behavior: 'smooth' }); document.querySelector('#app').focus({ preventScroll: true }); };
const route = () => setView(location.hash.slice(1).split('/')[0] || 'home');
addEventListener('hashchange', route);
const projectList = document.querySelector('#projectList');
const projectDetail = document.querySelector('#projectDetail');
const homeBoard = document.querySelector('.board-main');
const renderProject = (project) => `<article class="project-row" data-type="${project.type}" data-id="${project.id}"><span class="project-index">${project.year}</span><div><h3>${project.title}</h3><p>${project.label}</p></div><span class="project-status">${project.status}</span><span class="project-arrow">↗</span></article>`;
projectList.innerHTML = projects.map(renderProject).join('');
const openProject = (project) => { const visual = project.visual === 'image' ? '<img src="assets/authenticity.png" alt="Abstract digital face made from particles">' : project.visual === 'code' ? '<img src="assets/adversarial-examples.png" alt="Original and perturbed vegetation tiles with difference heatmaps">' : project.visual === 'ndvi' ? '<img src="assets/ndvi-matrix.png" alt="Confusion matrix for low, medium, and high vegetation classes">' : '<strong>FIELD NOTE<br>/ NEXT</strong>'; projectDetail.innerHTML = `<div class="detail-visual visual-${project.visual}">${visual}</div><div class="detail-copy"><div class="detail-top"><span>${project.label}</span><span>${project.status} / ${project.year}</span></div><h3>${project.title}</h3><p>${project.summary}</p><div class="method-list">${project.methods.map((method, index) => `<span><b>0${index + 1}</b>${method}</span>`).join('')}</div><a class="text-link" href="mailto:pandahat@uprm.edu?subject=${encodeURIComponent(project.title)}">Ask about this track ↗</a></div>`; projectDetail.classList.add('is-open'); };
projectList.addEventListener('click', event => { const row = event.target.closest('.project-row'); if (row) { document.querySelectorAll('.project-row.selected').forEach(item => item.classList.remove('selected')); row.classList.add('selected'); openProject(projects.find(project => project.id === row.dataset.id)); } });
document.querySelectorAll('.filter').forEach(filter => filter.addEventListener('click', () => { document.querySelectorAll('.filter').forEach(item => item.classList.remove('active')); filter.classList.add('active'); const type = filter.dataset.filter; document.querySelectorAll('.project-row').forEach(row => { row.hidden = type !== 'all' && row.dataset.type !== type; }); document.querySelector('#projectCount').textContent = `${[...document.querySelectorAll('.project-row:not([hidden])')].length.toString().padStart(2, '0')} tracks`; }));
document.querySelector('#memberGrid').innerHTML = members.map(member => `<article class="member-card"><div class="member-initials">${member.initials}</div><div><h3>${member.name}</h3><span>${member.role}</span></div><p>${member.detail}</p></article>`).join('');
const themeToggle = document.querySelector('#themeToggle'); const themeLabel = document.querySelector('#themeLabel'); const savedTheme = localStorage.getItem('pandahat-theme');
if (savedTheme) { document.body.dataset.theme = savedTheme; themeLabel.textContent = savedTheme === 'signal' ? 'Signal' : 'Fieldnotes'; }
themeToggle.addEventListener('click', () => { const next = document.body.dataset.theme === 'fieldnotes' ? 'signal' : 'fieldnotes'; document.body.dataset.theme = next; themeLabel.textContent = next === 'signal' ? 'Signal' : 'Fieldnotes'; localStorage.setItem('pandahat-theme', next); });
const menuToggle = document.querySelector('#menuToggle'); menuToggle.addEventListener('click', () => { const open = document.body.classList.toggle('menu-open'); menuToggle.setAttribute('aria-expanded', String(open)); });
document.querySelectorAll('.primary-nav a').forEach(link => link.addEventListener('click', () => { document.body.classList.remove('menu-open'); menuToggle.setAttribute('aria-expanded', 'false'); }));
addEventListener('scroll', () => { const max = document.documentElement.scrollHeight - innerHeight; document.querySelector('#progressBar').style.width = `${max ? scrollY / max * 100 : 0}%`; document.querySelector('.site-header').classList.toggle('scrolled', scrollY > 12); if (homeBoard) homeBoard.style.setProperty('--scroll-shift', `${Math.min(scrollY, 500) * -.035}px`); }, { passive: true });
route();
